### ISSUE TITLE
Election problem

### ISSUE THREAD

**Issue by yfei-z** [jgroups-extras/jgroups-raft#258]
I noticed that the election means of jgroups-raft has a little different from the standard algorithm, so I did some tests about it.
![raft-bug1](https://github.com/jgroups-extras/jgroups-raft/assets/4158629/e41c4bc0-dbe1-40f9-9cc0-07fbc3875aac)
There are 5 nodes of the cluster, and here is the log status of term 1. The steps like below:
1. Apply two commands with 5 nodes
2. Shutdown C then apply two commands
3. Shutdown E then apply two commands

![raft-bug2](https://github.com/jgroups-extras/jgroups-raft/assets/4158629/da0b5d66-150e-41aa-9741-5cb4f2c635a9)
Shutdown all nodes then restart C, D, E of the 5 nodes cluster, C first and it become the coordinator, then D and then E. The majority has been reached, so the coordinator begin the election process, after all responses have been received, coordinator begin to find out the leader, below is the source code.
```java
    protected Address determineLeader() {
        Address leader=null;
        Map<Address,VoteResponse> results=votes.getResults();
        for(Address mbr: view.getMembersRaw()) {
            VoteResponse rsp=results.get(mbr);
            if(rsp == null)
                continue;
            if(leader == null)
                leader=mbr;
            if(isHigher(rsp.last_log_term, rsp.last_log_index))
                leader=mbr;
        }
        return leader;
    }

    protected boolean isHigher(long last_term, long last_index) {
        long my_last_index=raft.log().lastAppended();
        LogEntry entry=raft.log().get(my_last_index);
        long my_last_term=entry != null? entry.term() : 0;
        if(last_term > my_last_term)
            return true;
        if(last_term < my_last_term)
            return false;
        return last_index > my_last_index;
    }
```
`view.getMembersRaw()` returns "C, D, E" which is the joining order of them, and the "self" here is C which is the coordinator, the result is E become the leader of term 2.

![raft-bug3](https://github.com/jgroups-extras/jgroups-raft/assets/4158629/e896ce19-e9bc-4a9c-aa56-1a81b2b43ff0)
Trying to setAsync a command, after the log being committed and applied, the log like above.

**Comment by jabolina** [comment]
Thanks for opening the issue, @yfei-z. I think b87f5f3d195e5f9fe75c1f7e05a8213b0d112c21 fixes this issue, a problem in calculating the longest log. I'll try to create a test with the scenario described to make sure and release a new version with the fix ASAP.

**Comment by jabolina** [comment]
I developed a small test with the scenario to try. Running against main, the correct node (`D`) is elected. And without b87f5f3d195e5f9fe75c1f7e05a8213b0d112c21, the wrong node is elected. An equivalent of this scenario is https://github.com/jgroups-extras/jgroups-raft/blob/d8aedcb3753b404e621983f195023c7c1cae4870/tests/junit-functional/org/jgroups/tests/ElectionsTest.java#L66

I'll run a few more tests and try to release 1.0.13.Final this week. I'll close this one, thanks for reporting!
